(()=>{if(window.__FADJA_INSTALL__)return;window.__FADJA_INSTALL__=1;
const css=document.createElement('style');css.textContent=`
.fadja-install-modal{position:fixed;inset:0;background:#050b20cc;z-index:99999;display:none;place-items:center;padding:20px}
.fadja-install-modal.on{display:grid}.fadja-install-card{width:min(760px,100%);max-height:92vh;overflow:auto;background:var(--bg,#fff);color:var(--ink,#101a38);border:1px solid var(--line,#dfe5f2);border-radius:22px;padding:26px;box-shadow:0 30px 80px #0008}
.fadja-install-head{display:flex;justify-content:space-between;gap:16px;align-items:flex-start}.fadja-install-head h2{margin:0}.fadja-install-x{all:unset;cursor:pointer;font-size:28px;line-height:1;padding:4px 8px}
.fadja-install-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(210px,1fr));gap:12px;margin-top:18px}.fadja-install-item{border:1px solid var(--line,#dfe5f2);border-radius:14px;padding:16px}
.fadja-install-item b{display:block;margin-bottom:5px}.fadja-install-item p{font-size:13px;color:var(--mut,#64708f);margin:0 0 12px}.fadja-install-item button{width:100%}
.fadja-install-note{margin-top:16px;padding:12px 14px;background:var(--soft,#f3f6fd);border-radius:12px;color:var(--mut,#64708f);font-size:12px}
.fadja-install-native{margin-top:12px;padding:12px 14px;border:1px dashed var(--line,#dfe5f2);border-radius:12px;font-size:12px;color:var(--mut,#64708f)}
`;document.head.appendChild(css);
if(!document.querySelector('link[rel="manifest"]')){const l=document.createElement('link');l.rel='manifest';l.href='manifest.webmanifest';document.head.appendChild(l)}
[['theme-color','#0A1A4F'],['apple-mobile-web-app-capable','yes'],['apple-mobile-web-app-status-bar-style','black-translucent'],['apple-mobile-web-app-title','FADJA']].forEach(([n,c])=>{if(!document.querySelector('meta[name="'+n+'"]')){const m=document.createElement('meta');m.name=n;m.content=c;document.head.appendChild(m)}});
let deferred=null;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferred=e;window.dispatchEvent(new Event('fadja-install-ready'))});
const ios=/iphone|ipad|ipod/i.test(navigator.userAgent),android=/android/i.test(navigator.userAgent),standalone=()=>matchMedia('(display-mode: standalone)').matches||navigator.standalone===true;
function modal(){let m=document.getElementById('fadja-install-modal');if(m)return m;m=document.createElement('div');m.id='fadja-install-modal';m.className='fadja-install-modal';m.innerHTML=`<div class="fadja-install-card"><div class="fadja-install-head"><div><h2>Installer l’application FADJA</h2><p class="lead">Une seule application web installable sur téléphone, tablette et ordinateur.</p></div><button class="fadja-install-x" aria-label="Fermer">×</button></div>
<div class="fadja-install-grid">
<div class="fadja-install-item"><b>Android</b><p>Installation directe de FADJA comme application depuis Chrome.</p><button class="btn" data-install>Installer sur Android</button></div>
<div class="fadja-install-item"><b>iPhone / iPad</b><p>Installation directe comme app web depuis Safari.</p><button class="btn" data-ios>Installer sur iPhone / iPad</button></div>
<div class="fadja-install-item"><b>Windows / macOS / Linux</b><p>Installation comme application depuis Chrome ou Edge.</p><button class="btn" data-install>Installer sur ordinateur</button></div>
<div class="fadja-install-item"><b>Android / installation app</b><p>La version installable FADJA fonctionne directement depuis le navigateur. Elle ne nécessite pas de fichier APK.</p><button class="btn o" data-install-now>Installer FADJA</button></div>
</div><div class="fadja-install-native">Version Android PWA : installation immédiate depuis le navigateur. Un vrai APK natif pourra être branché ici dès qu’un fichier APK signé est fourni. Aucun faux lien APK n’est créé.</div><div class="fadja-install-note" id="fadja-install-status">Choisissez votre appareil pour lancer l’installation.</div></div>`;document.body.appendChild(m);m.addEventListener('click',e=>{if(e.target===m||e.target.closest('.fadja-install-x'))m.classList.remove('on')});m.querySelectorAll('[data-install]').forEach(b=>b.onclick=install);m.querySelector('[data-ios]').onclick=iosHelp;return m}
async function install(){const m=modal(),s=m.querySelector('#fadja-install-status');m.classList.add('on');if(standalone()){s.textContent='FADJA est déjà installée sur cet appareil.';return}if(deferred){deferred.prompt();const r=await deferred.userChoice;s.textContent=r.outcome==='accepted'?'Installation lancée.':'Installation annulée.';deferred=null;return}if(ios){iosHelp();return}if(android)s.innerHTML='<b>Android :</b> Chrome doit afficher l’option d’installation. Si elle n’apparaît pas, ouvrez le menu ⋮ puis <b>Installer l’application</b> ou <b>Ajouter à l’écran d’accueil</b>.';else s.innerHTML='<b>Ordinateur :</b> Chrome/Edge → icône <b>Installer</b> dans la barre d’adresse, ou menu du navigateur → <b>Installer FADJA</b>.'}
function iosHelp(){const m=modal(),s=m.querySelector('#fadja-install-status');m.classList.add('on');s.innerHTML='<b>iPhone / iPad :</b> ouvrez FADJA dans <b>Safari</b> → <b>Partager</b> → <b>Sur l’écran d’accueil</b> → <b>Ajouter</b>.'}
function open(){modal().classList.add('on');}
function bind(){document.querySelectorAll('#inst,[data-install-app],a,button').forEach(el=>{if(el.dataset.fadjaInstallBound)return;const t=(el.textContent||'').toLowerCase();if(el.id==='inst'||el.hasAttribute('data-install-app')||t.includes("installer l'app")||t.includes("installer l’application")||t.includes("télécharger l’application")){el.dataset.fadjaInstallBound='1';el.addEventListener('click',e=>{e.preventDefault();if(el.hasAttribute('data-fadja-ios'))iosHelp();else open()},{capture:true})}})}
bind();new MutationObserver(bind).observe(document.body,{childList:true,subtree:true});window.addEventListener('fadja-install-ready',bind);
if('serviceWorker' in navigator&&location.protocol.startsWith('http'))navigator.serviceWorker.register('sw.js?v=20261003-3',{updateViaCache:'none'}).catch(()=>{});
})();